runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app
instance_class: F2


runtime_config:
    operating_system: "ubuntu22"
    runtime_version: "3.11"


handlers:
- url: /.*
  script: auto
  redirect_http_response_code: 301
